module.exports = {
	"extends": "eslint:recommended",
	"rules": {
		// Possible Errors
		"no-console": "warn",
		"no-template-curly-in-string": "error",
		"valid-jsdoc": "warn",
		// Best Practices
		"array-callback-return": "error",
		"dot-notation": "warn",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-implied-eval": "error",
		"no-invalid-this": "error",
		"no-lone-blocks": "error",
		"no-multi-spaces": "warn",
		"no-new": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-octal-escape": "error",
		"no-proto": "error",
		"no-return-assign": "error",
		"no-return-await": "warn",
		"no-script-url": "warn",
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-throw-literal": "error",
		"no-unmodified-loop-condition": "warn",
		"no-unused-expressions": "warn",
		"no-useless-call": "warn",
		"no-useless-concat": "warn",
		"no-useless-return": "warn",
		"no-void": "error",
		"no-with": "warn",
		"yoda": ["error", "never", {"exceptRange": true}],
		// Variables
		"no-shadow": "warn",
		"no-shadow-restricted-names": "error",
		"no-undef-init": "warn",
		// Node.js and CommonJS
		"callback-return": "warn",
		"global-require": "warn",
		// Stylistic Issues
		"array-bracket-spacing": "warn",
		"block-spacing": "warn",
		"brace-style": "error",
		"camelcase": "error",
		"comma-dangle": "error",
		"comma-spacing": "warn",
		"comma-style": "error",
		"computed-property-spacing": "error",
		"func-call-spacing": "error",
		"func-name-matching": "error",
		"function-paren-newline": ["error", "never"],
		"implicit-arrow-linebreak": ["error", "beside"],
		"indent": ["error", "tab"],
		"key-spacing": "error",
		"keyword-spacing": "error",
		"lines-between-class-members": "error",
		"new-parens": "error",
		"no-array-constructor": "error",
		"no-continue": "warn",
		"no-mixed-operators": "error",
		"no-multi-assign": "error",
		"no-multiple-empty-lines": "warn",
		"no-negated-condition": "warn",
		"no-nested-ternary": "error",
		"no-new-object": "warn",
		"no-restricted-syntax": ["warn", "ForInStatement", "ForOfStatement"], // Use forEach etc. instead
		"no-trailing-spaces": "warn",
		"no-unneeded-ternary": "error",
		"no-whitespace-before-property": "error",
		"nonblock-statement-body-position": "error",
		"object-curly-spacing": "error",
		"padded-blocks": ["warn", "never"],
		"quotes": ["error", "double", { "allowTemplateLiterals": true }],
		"semi": "error",
		"semi-spacing": "error",
		"semi-style": "error",
		"space-before-function-paren": ["error", "never"],
		"space-in-parens": "error",
		"space-infix-ops": "error",
		"space-unary-ops": "error",
		"spaced-comment": "error",
		"switch-colon-spacing": "error",
		"template-tag-spacing": "error",
		"unicode-bom": "error"
	}
};